/**
 * This class is generated by jOOQ
 */
package jooq;


import javax.annotation.Generated;

import jooq.tables.Meeting;
import jooq.tables.records.MeetingRecord;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<MeetingRecord, Integer> IDENTITY_MEETING = Identities0.IDENTITY_MEETING;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<MeetingRecord> MEETING_PKEY = UniqueKeys0.MEETING_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<MeetingRecord, Integer> IDENTITY_MEETING = createIdentity(Meeting.MEETING, Meeting.MEETING.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<MeetingRecord> MEETING_PKEY = createUniqueKey(Meeting.MEETING, Meeting.MEETING.ID);
	}
}
