/**
 * This class is generated by jOOQ
 */
package jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.Keys;
import jooq.Public;
import jooq.tables.records.MeetingRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Meeting extends TableImpl<MeetingRecord> {

	private static final long serialVersionUID = 1370125599;

	/**
	 * The reference instance of <code>public.meeting</code>
	 */
	public static final Meeting MEETING = new Meeting();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MeetingRecord> getRecordType() {
		return MeetingRecord.class;
	}

	/**
	 * The column <code>public.meeting.id</code>.
	 */
	public final TableField<MeetingRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.meeting.organizer</code>.
	 */
	public final TableField<MeetingRecord, String> ORGANIZER = createField("organizer", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.meeting.topic</code>.
	 */
	public final TableField<MeetingRecord, String> TOPIC = createField("topic", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.meeting.description</code>.
	 */
	public final TableField<MeetingRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>public.meeting</code> table reference
	 */
	public Meeting() {
		this("meeting", null);
	}

	/**
	 * Create an aliased <code>public.meeting</code> table reference
	 */
	public Meeting(String alias) {
		this(alias, MEETING);
	}

	private Meeting(String alias, Table<MeetingRecord> aliased) {
		this(alias, aliased, null);
	}

	private Meeting(String alias, Table<MeetingRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<MeetingRecord, Integer> getIdentity() {
		return Keys.IDENTITY_MEETING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<MeetingRecord> getPrimaryKey() {
		return Keys.MEETING_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<MeetingRecord>> getKeys() {
		return Arrays.<UniqueKey<MeetingRecord>>asList(Keys.MEETING_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Meeting as(String alias) {
		return new Meeting(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Meeting rename(String name) {
		return new Meeting(name, null);
	}
}
